### ISSUE TITLE
КР-1 2018-2019, задача 1

### ISSUE THREAD

**Issue by elizacc** [bdemeshev/em301#3]
Возможно в задаче 1 (основной части) неправильный ответ.
Если обозначить случайную величину (X+Y)/X за Z/3, то Z имеет распределение Фишера с 15, 5 степенями свободы и тогда ответ отличается от полученного в текущем решении

**Comment by bdemeshev** [comment]
Ох, случайно нашёл здесь этот issue :) 
Из-за того, что X и Y зависимы нужно от (X+Y)/X переходить к Y/X, Лиз! 
И там будет Фишер 10, 5.
issue по подборке экзаменов тут:
https://github.com/bdemeshev/metrics_hse_exams/issues
